-------------------------------------------------
-- People over 40
CREATE VIEW PEOPLE_OVER_40
AS
    SELECT PERSON_ID, NAME, NICKNAME, GENDER, AGE, JOB
    FROM PEOPLE
    WHERE AGE > 40;
-------------------------------------------------
--Weekly winners
CREATE VIEW WEEKLY_WINNER
AS
    SELECT PARTICIPANT_ID,NAME,EPISODE_ID,SEASON_ID,POINTS
    FROM  RATED_IN , PEOPLE
    WHERE RATED_IN.PARTICIPANT_ID = PEOPLE.PERSON_ID
    AND RATED_IN.POINTS = 10;
-------------------------------------------------
CREATE VIEW MALE_WITH_NICKNAME
AS
	SELECT *
	FROM PEOPLE
	WHERE GENDER = 'M'
	AND NICKNAME != 'NULL'
	
------------------------------------------------
CREATE VIEW PEOPLE_BEING_MADONNA
AS
    SELECT PERSON_ID, NAME, NICKNAME,SEASON_ID,EPISODE_ID
    FROM GENERATED_IMPRESSION, PEOPLE
    WHERE GENERATED_IMPRESSION.PARTICIPANT_ID = PEOPLE.PERSON_ID
    AND GENERATED_IMPRESSION.SINGER_NAME='Madonna'
    OR GENERATED_IMPRESSION.PARTICIPANT_ID = PEOPLE.PERSON_ID AND GENERATED_IMPRESSION.SINGER_NAME='Madona';